### ISSUE TITLE
Use per-requirement consortium mapping

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jasmin-manage#3]
Project has "default" consortium if known at creation time, but project creation without consortium is permitted.

At the point where a service is created, the project must either have a default consortium or one must be specified.

**Comment by mkjpryor-stfc** [comment]
@mjpritchard 

I've been thinking about this and I think it might actually be better to move to the requirement level.

The consortium thing is really just for accounting. If each requirement could belong to a different consortium, even within a single service, that allows for some interesting things like a GWS having some of its allocation for the same resource (e.g. SOF) from consortium A and some from consortium B. In terms of what is provisioned, this could be manifested as a single SOF volume of size req(A) + req(B), but the fact it came from two consortiums would be recorded.

What do you think?

**Comment by mjpritchard** [comment]
Actually that sounds quite sensible & useful. Would be good to set the default for the requirement to something sensible however (i.e. the main/dominant consortium of what's been provisioned so far for that project, if that can be deduced?). But please go ahead, sounds good.

**Comment by mkjpryor-stfc** [comment]
@mjpritchard

We already discussed that projects would have an optional default consortium, which would be used as the default.

In the case when a default consortium for the project is not set, we could use the consortium with the most requirements in the project. Doesn't help with the first requirement though. Or do you think project-default-consortium is sufficient?

**Comment by mkjpryor-stfc** [comment]
Implemented in 45eed0e
