### ISSUE TITLE
Need ability to hide some categories of service

### ISSUE THREAD

**Issue by mjpritchard** [cedadev/jasmin-manage#30]
Example: "External Tenancy MCP", "Managed Tenancy MCP" are both deprecated, though we have current instances of them (which still need to be managed for now).
But when setting up a new project, we don't want users to be able to select them as an option.

**Comment by mjones07** [comment]
Only show the options for categories which have a quota for the consortium when creating a service.

**Comment by mjones07** [comment]
Add a "is public" flag to the category, like we do with the consortia

**Comment by nf679** [comment]
Added in #49
