### ISSUE TITLE
List GWSs by consortia or by funding source NCEO or NCAS

### ISSUE THREAD

**Issue by philipkershaw** [cedadev/jasmin-manage#37]
@mjpritchard, coming from a CEDA EO meeting today, there's an ask to be able to display a list of GWSs that are associated with NCEO. Is anything like this possible or at least to list GWSs belonging to a given consortia

**Comment by mjones07** [comment]
Needs a solution defining.

Use cases:
  - filter by category and consortium
  - If we want to do by funding source we need a new field for the funding source/ reference

**Comment by mjpritchard** [comment]
See also #32 (tags) which is be relevant given funding / commnunity entities might not map directly onto consortia
