### ISSUE TITLE
Provide tooltips for icons

### ISSUE THREAD

**Issue by mjpritchard** [cedadev/jasmin-manage#39]
Icons in GUI need rollover tooltips to make their meaning more obvious.
Example: paper-plane icon representing "requested" status of a requirement.
See this conversation: 
https://ncas-talk.slack.com/archives/C0UR29PPX/p1667903673615279

**Comment by mjones07** [comment]
Sorted in 8652b3c70d7552e80a82604e38273d338e9d0f0e
