### ISSUE TITLE
Structured metadata for requirements

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jasmin-manage#4]
Allow metadata to be attached to requirements where the structure is defined by the resource.

**Comment by mkjpryor-stfc** [comment]
@mjpritchard 

Can you remember what the use case for this was?

It is quite a complicated change, so would be nice not to do it. Happy to have a chat to discuss if you want.

**Comment by mjpritchard** [comment]
Sorry, no. Might become apparent with testing...

**Comment by mkjpryor-stfc** [comment]
WONTFIX
