### ISSUE TITLE
Make it clearer whether a requirement is for the delta or the new total

### ISSUE THREAD

**Issue by mjpritchard** [cedadev/jasmin-manage#41]
A requirement for 20 TB could be interpreted as 20 TB new space, or 20 TB total (on top of an existing provision). Need to agree a convention then stick to it and make it clear in the GUI. (we have a mixture of existing cases!)

**Comment by mjones07** [comment]
Comment on the pop-up asking that if there's an existing requirement for this, only request the change, not the new total.

**Comment by mjones07** [comment]
Want to make it clearer in the UI to _not_ request a delta, that all requirements should be the total which is needed.
